version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:guardia123@localhost/ms_user
      - JWT_SECRET_KEY=teste
      - JWT_REFRESH_SECRET_KEY=guardia
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_MINUTES=10080
      - HOST=0.0.0.0
      - PORT=8000

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=guardia
      - POSTGRES_PASSWORD=guardia123
      - POSTGRES_DB=postgres
