"""empty message

Revision ID: 145144694dae
Revises: 5b4d1e083261
Create Date: 2023-07-25 08:16:29.666228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145144694dae'
down_revision = '5b4d1e083261'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
