"""empty message

Revision ID: 42816c33f2c3
Revises: b0f1bf961313
Create Date: 2023-07-25 08:41:14.969799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42816c33f2c3'
down_revision = 'b0f1bf961313'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
