"""empty message

Revision ID: 4f25a0611a29
Revises: 653044ad12b3
Create Date: 2023-07-23 18:13:27.004724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f25a0611a29'
down_revision = '653044ad12b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responsible_for', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('responsible_for_responsible_user_id_fkey', 'responsible_for', type_='foreignkey')
    op.create_foreign_key(None, 'responsible_for', 'users', ['user_id'], ['id'])
    op.drop_column('responsible_for', 'responsible_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responsible_for', sa.Column('responsible_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'responsible_for', type_='foreignkey')
    op.create_foreign_key('responsible_for_responsible_user_id_fkey', 'responsible_for', 'users', ['responsible_user_id'], ['id'])
    op.drop_column('responsible_for', 'user_id')
    # ### end Alembic commands ###
