"""empty message

Revision ID: 5b4d1e083261
Revises: 4f25a0611a29
Create Date: 2023-07-25 07:52:23.854930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4d1e083261'
down_revision = '4f25a0611a29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responsible_for', 'entity_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responsible_for', sa.Column('entity_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
