"""empty message

Revision ID: 671741fa516b
Revises: 0de30c968154
Create Date: 2023-07-05 15:56:00.036918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671741fa516b'
down_revision = '0de30c968154'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
