"""empty message

Revision ID: b0a6dd0f8cde
Revises: 42816c33f2c3
Create Date: 2023-07-25 08:44:37.814837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a6dd0f8cde'
down_revision = '42816c33f2c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
