"""empty message

Revision ID: b0f1bf961313
Revises: 145144694dae
Create Date: 2023-07-25 08:31:36.760017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f1bf961313'
down_revision = '145144694dae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_responsible_for_id', table_name='responsible_for')
    op.drop_table('responsible_for')
    op.add_column('users', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'parent_id')
    op.create_table('responsible_for',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='responsible_for_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='responsible_for_pkey')
    )
    op.create_index('ix_responsible_for_id', 'responsible_for', ['id'], unique=False)
    # ### end Alembic commands ###
