"""empty message

Revision ID: b1f97b071f64
Revises: 671741fa516b
Create Date: 2023-07-22 11:52:36.816512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f97b071f64'
down_revision = '671741fa516b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('has_access', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('responsible_for_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_user_type'), 'users', ['user_type'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['responsible_for_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_user_type'), table_name='users')
    op.drop_column('users', 'updated')
    op.drop_column('users', 'created')
    op.drop_column('users', 'responsible_for_id')
    op.drop_column('users', 'has_access')
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###
